version: 2

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
      - image: mongo:3.4.4
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: lein-deps-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/project/.m2
            - ~/project/.lein
          key: lein-deps-{{ checksum "project.clj" }}
      - run: lein do fetch --no-card-images, test